# Generated by Django 4.2 on 2023-04-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='company',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ManyToManyField(to='api.company'),
        ),
    ]
